#include "GamePlay.h"
#include "Game.h"

#include <godot_cpp/classes/input_event.hpp>
#include <godot_cpp/classes/input_event_action.hpp>
#include <godot_cpp/classes/label.hpp>
#include <godot_cpp/classes/sprite2d.hpp>
#include <godot_cpp/classes/image_texture.hpp>

using namespace godot;
using namespace std;

GameState GamePlay::current_state_ = GameState{0, 0};
ResourcePreloader * GamePlay::bkgloader_ = nullptr;
ResourcePreloader * GamePlay::charloader_ = nullptr;
Sprite2D * GamePlay::character_left = nullptr;
Sprite2D * GamePlay::character_right = nullptr;
Label * GamePlay::name_ = nullptr;
Label * GamePlay::content_ = nullptr;
bool GamePlay::is_reviewing = false;
GamePlay * GamePlay::this_ptr = nullptr;

GamePlay::GamePlay() {
  this_ptr = this;
}

GamePlay::~GamePlay() {

}

void GamePlay::_bind_methods() {
  ADD_SIGNAL(MethodInfo("call_change_bkg", PropertyInfo(Variant::STRING, "bkg_name")));
  ADD_SIGNAL(MethodInfo("call_play_music", PropertyInfo(Variant::STRING, "music_name")));
}

void GamePlay::_ready() {
  // 这里用于初始化各个对象指针
  input_ = Input::get_singleton();
  character_left = get_node<Sprite2D>("LeftChar");
  character_right = get_node<Sprite2D>("RightChar");
  name_ = get_node<Label>("Dialog/Name");
  content_ = get_node<Label>("Dialog/Content");
}

void GamePlay::_gui_input(const Ref<InputEvent> &event) {
//  if (event->is_class("InputEventAction")) {
//    if (static_cast<Ref<InputEventAction>>(event)->is_action_pressed("ui_accept")) {
//      step();
//    }
//  }
//  if (event->is_class("InputEventAction")) {
//    if (static_cast<Ref<InputEventAction>>(event)->is_action_pressed("ui_cancel")) {
//      static_cast<Game*>(get_parent())->return_to_main_menu();
//    }
//  }
}

void GamePlay::_process(double delta) {
  if (this->is_visible()) {
    if (input_->is_action_just_pressed("ui_accept")) {
      step();
    } else if (input_->is_action_just_pressed("ui_cancel")) {
      current_state_.step_ -= (current_state_.step_ > 0);
      static_cast<Game*>(get_parent())->return_to_main_menu();
    } else if (input_->is_action_just_pressed("ui_undo")) {
      rstep();
    };
    if (input_->is_action_pressed("skip")) {
      step();
    }
  }
}

void GamePlay::step() {
  switch (current_state_.chapter_) {
    case 0:
      cp0[current_state_.step_]();
      break;
    case 1:
      cp1[current_state_.step_]();
      break;
    case 2:
      cp2[current_state_.step_]();
      break;
    case 3:
      cp3[current_state_.step_]();
      break;
    case 4:
      static_cast<Game*>(get_parent())->finished();
      static_cast<Game*>(get_parent())->return_to_main_menu();
      break;
    default:
      static_cast<Game*>(get_parent())->return_to_main_menu();
      break;
  }
  current_state_.step_++;
}

void GamePlay::rstep() {
  if (current_state_.step_ > 1) {
    current_state_.step_--;
  }

  switch (current_state_.chapter_) {
    case 0:
      cp0[current_state_.step_ - 1]();
      break;
    case 1:
      cp1[current_state_.step_ - 1]();
      break;
    case 2:
      cp2[current_state_.step_ - 1]();
      break;
    case 3:
      cp3[current_state_.step_ - 1]();
      break;
    default:
      static_cast<Game*>(get_parent())->return_to_main_menu();
      break;
  }
}

void GamePlay::ss(
      const String& name,
      const String& dialog,
      const String& background,
      const String& left_character,
      const String& right_character,
      const String& background_music
    ) {

  if (name == L"旁白") {
    name_->set_visible(false);
  } else {
    name_->set_visible(true);
    name_->set_text(L"【" + name + L"】");
  }

  if (dialog != "None") {
    content_->set_text(dialog);
  }

  if (left_character == "None") {
    character_left->set_visible(false);
  } else {
    character_left->set_visible(true);
    character_left->set_texture(
        charloader_->get_resource(left_character));
  }

  if (right_character == "None") {
    character_right->set_visible(false);
  } else {
    character_right->set_visible(true);
    character_right->set_texture(
        charloader_->get_resource(right_character));
  }

  this_ptr->emit_signal("call_change_bkg", background);
  this_ptr->emit_signal("call_play_music", background_music);
}

vector<function<void()>> GamePlay::init_cp0() {
  return {
    [](){
      ss(
        L"旁白",
        L"1941年，上海。",
        "None",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"「海上花」当中的这一天并没有什么不同",
        "None",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"作为一间酒馆，并且同时经营有住宿业务，「海上花」的工作时段主要在晚间，因此其中人们会选择白天休息。",
        "None",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"酒馆的掌柜是林如意，因为她还有清晨送客的工作，所以会将整个下午的时间都用作睡眠。",
        "None",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"酒馆的二掌柜是林心诚，她也是林如意的独生女。",
        "None",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「呼……」",
        "xincheng_waking_up",
        "None",
        "None",
        "a_quiet_day"
          );
    },//开始编辑
    [](){
      ss(
        L"旁白",
        L"不同于她的母亲，心诚每天在接近中午时起床，并在洗漱后享用佣人们提前准备好的午餐。",
        "xincheng_waking_up",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「又到了起床的时间了吗……美好的时光可真是短暂呢。」",
        "xincheng_waking_up",
        "xincheng_thinking",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"事实上她只有14岁，却因为许多原因，变得相当成熟、可靠。",
        "xincheng_waking_up",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"尽管性格有些散漫，心诚遇事时机敏的反应与严谨的态度使她足以负起掌柜的责任。",
        "xincheng_waking_up",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"嗯，准备好就出发吧。",
        "xincheng_waking_up",
        "xincheng_normal",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"她很快完成了午间的例行事务，随后回到自己的房间。",
        "None",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"期间，楼中人们会打扫、整理好店面，不时也会有人来汇报一些事宜，而她则会一一处理。",
        "None",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"而在其余时间里，下午会是她读书与学习的时间，她也会阅读一些报纸，以了解时事。",
        "None",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「国内的战事还是这样没完没了。」",
        "xincheng_reading",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「不知道这块租界还能平安到什么时候。」",
        "xincheng_reading",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"她从来没有去上过学。",
        "xincheng_reading",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"不过除去报刊、文艺类书籍外，一些基础的理学知识也会出现在她的学习书目内。",
        "xincheng_reading",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"算术之类……对掌柜而言也是相当常见的工具。",
        "xincheng_reading",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"在这样的动乱年代，不去上学而就这样早早当家也许会更好吧。",
        "xincheng_reading",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"至少她们母女二人都这么认为。",
        "xincheng_reading",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"看起来林心诚对待学习的态度相当懒散，毕竟读书对她而言少有目的性，只是兴趣使然。",
        "xincheng_reading",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"她正毫不认真地翻看着一些报纸。",
        "xincheng_reading",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"出于许多原因，她并不想过多地参与到周遭的政治斗争中，这也是林如意常常告诉她的准则。",
        "xincheng_reading",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"「就这样平静地生活下去吧。」",
        "xincheng_reading",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"时间很快将要来到傍晚。",
        "None",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"从外部看来，「海上花」酒馆的陈设相当精美。",
        "bar_overview",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"相对宏伟的外表之下，内部装点也无比细致。",
        "bar_overview",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"但与此毫不相称的是，其中酒菜价格却相当低廉，即使是普通民众，也可以轻松享用而不会有太多压力。",
        "bar_overview",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"正因如此，加之店内妥善的管理以及几乎与时代无缘的和谐氛围，「海上花」在周遭可谓无人不知，每晚客人络绎不绝。",
        "bar_overview",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"今天也只是一个平常的工作日。",
        "bar_inside_2",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"心诚在前店后屋里来回走动，帮助协调伙计们的工作。",
        "bar_inside_2",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"掌柜林如意则坐镇在柜台，负责接待工作之类。",
        "bar_inside_2",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"事情处理妥当了，林心诚走进客人当中，与他们攀谈说笑。",
        "bar_inside_2",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"店里的客人们也都相当喜爱这位可爱有趣的小姑娘。",
        "bar_inside_2",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"这样温馨、繁忙的工作场景一直持续，直到——",
        "bar_inside_2",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"一位客人的到来，使周遭的氛围开始发生一些微妙的改变。",
        "bar_inside_2",
        "xincheng_serious",
        "patron_0",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"他看起来相当阔气，在附近这一带，富裕人家其实并不鲜见。",
        "bar_inside_2",
        "xincheng_serious",
        "patron_0",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"不过他这一趟并非为了饮酒。",
        "bar_inside_2",
        "xincheng_serious",
        "patron_0",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"只见他走向林心诚，凑近她的耳边轻声问道——",
        "bar_inside_2",
        "xincheng_serious",
        "patron_0",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"嫖客",
        L"「何处寻芳径……」",
        "bar_inside_2",
        "xincheng_serious",
        "patron_0",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「觅春风？」",
        "bar_inside_2",
        "xincheng_serious",
        "patron_0",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"这是一句暗语，作为「海上花」二掌柜的林心诚自然明白其中意思。",
        "bar_inside_2",
        "xincheng_serious",
        "patron_0",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「我知道了。请这位客人莫要着急，我现在就带您去后店。」",
        "bar_inside_2",
        "xincheng_gently_smile",
        "patron_0",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"嫖客",
        L"「有劳了。」",
        "bar_inside_2",
        "xincheng_serious",
        "patron_0",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"仅仅凭借「海上花」中售卖酒水带来的微薄利润自然不足以支撑其大量的消耗。",
        "None",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"因此「这种生意」对于她们而言可谓不可或缺。",
        "None",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"这位客人事实上是海上花的老主顾。",
        "None",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"每每造访，都会在这里耗费重金，只为求得一夜的欢乐流连。",
        "None",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"通过优质而廉价的酒品获得名声，同时暗中借此赚取高额利润。",
        "None",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"「海上花」通过这种方式实现了名利双收，对于客人们而言，或许也是一种利好吧。",
        "None",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      // 章节结束
      if (is_reviewing) {
        current_state_.chapter_ = -4;
      }
      current_state_.chapter_++;
      current_state_.step_ = 0;
    }
  };
}

vector<function<void()>> GamePlay::init_cp1() {
  return {
    [](){
      ss(
        L"旁白",
        L"今日的准备状况一如往常。",
        "None",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"刚刚开业的店里还没有什么客人。",
        "bar_inside_clear",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"就在这个时候，店里走进了一位银发男子。",
        "bar_inside_clear",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"因为目前没有什么其他的事情要做，林心诚打算亲自去接待他。",
        "bar_inside_clear",
        "ling_normal",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「先生您好，欢迎光顾小店！请问您那边总共几位，需要来一点什么呢？」",
        "bar_inside_clear",
        "xincheng_smile",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"银发男子",
        L"「这里便是「海上花」了，对吗？看起来确实相当不错。」",
        "bar_inside_clear",
        "xincheng_smile",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"银发男子",
        L"「我只有自己一个人，酒品就不必了，请问这里有茶饮之类的吗？」",
        "bar_inside_clear",
        "xincheng_smile",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「嗯嗯，本店里也有红茶和绿茶，不过因为我们不主营茶饮所以品类不多。请问您想要哪一种呢？」",
        "bar_inside_clear",
        "xincheng_smile",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"银发男子",
        L"「上一壶红茶就好。」",
        "bar_inside_clear",
        "xincheng_smile",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「好嘞，请您稍等，马上就来。」",
        "bar_inside_clear",
        "xincheng_smile",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"随后他便走到吧台边最靠近角落的座位，坐下来静静地读起了报纸。",
        "bar_inside_clear",
        "xincheng_smile",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"单独一个人过来又不喝酒……感觉这个人真的很奇怪。",
        "bar_inside_clear",
        "xincheng_normal",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"看样子他是第一次来，听口音应该不是本地人。",
        "bar_inside_clear",
        "xincheng_thinking",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"最近逃荒到租界的人并不在少数，不过如果跑这么远的话……加上他从容的样子，应该不是逃荒。",
        "bar_inside_clear",
        "xincheng_thinking",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"那他会是来做什么的呢？",
        "bar_inside_clear",
        "xincheng_thinking",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"心诚已经准备好了茶点，准备给他送过去，也打算借机和他聊上几句。",
        "bar_inside_clear",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「您好！这是您要的红茶，还请慢用。」",
        "bar_inside_clear",
        "xincheng_smile",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"银发男子",
        L"「嗯……」",
        "bar_inside_clear",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"她正在端详着那个人手上的报纸。",
        "bar_inside_clear",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"那是一份日文报纸，心诚能够看懂里面的一部分内容，基本说的都是前线胜利的消息。",
        "bar_inside_clear",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"银发男子",
        L"「偷窥别人的东西可不那么礼貌哦……不过……你能看得懂这些吗？」",
        "bar_inside_clear",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「被发现了呀……」",
        "bar_inside_clear",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「其实我勉强能看懂一些，因为经常会有日本人过来，所以我就稍微学习了一点日语。」",
        "bar_inside_clear",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"银发男子",
        L"「哈哈，看起来你还挺厉害的嘛。」",
        "bar_inside_clear",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「哎……先生过奖了！」",
        "bar_inside_clear",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"这突如其来的夸赞让心诚有点惊讶，不过同时也让她松了一口气——",
        "bar_inside_clear",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"眼前的这个人虽然看起来有些古怪，不过其实为人相当和善亲切。",
        "bar_inside_clear",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"应当是可以好好交流的吧？",
        "bar_inside_clear",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"心诚就这样望着他等候了许久，店里也逐渐来了许多客人。",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「请问先生你叫什么名字呢？看起来您不像是本地人的样子，为什么会想到来上海？」",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"银发男子",
        L"「你问……我嘛？」",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"他不紧不慢地翻着手中的报纸，看起来相当悠闲，也挺有兴趣陪着心诚聊下去的样子。",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「你可以叫我马灵，我的确是从外地来的，因为工作原因到上海这边来，以后应该会在这里居住很长一段时间吧。」",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「方便透露一下您来这里做的是什么样的工作吗？」",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"的确……很难想象在这样的时代中，他会因为什么样的工作特意跑到这里来。",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「这个嘛……如果我不想要告诉你呢？」",
        "bar_inside_4",
        "xincheng_normal",
        "ling_smile",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"他的语气像是在同小孩子说笑一样，反而不像是在隐瞒什么秘密",
        "bar_inside_4",
        "xincheng_normal",
        "ling_smile",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"如果真的想要这样做的话，也应该早早编好一个可信的理由糊弄过去才对吧。",
        "bar_inside_4",
        "xincheng_normal",
        "ling_smile",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"心诚这样想着，但也不得不应和着马灵的话语，就这样结束这一话题。",
        "bar_inside_4",
        "xincheng_normal",
        "ling_smile",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「好的……这样我也就不多问了。」",
        "bar_inside_4",
        "xincheng_thinking",
        "ling_smile",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"此后两人都平静了许久，店里依然同往常一样繁忙，直到……",
        "bar_inside_4",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"看起来今晚来了个麻烦的人物呢……",
        "bar_inside_4",
        "xincheng_normal",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"她说的是从门里进来的这个人，看起来他像是一个日本军官。",
        "bar_inside_4",
        "xincheng_normal",
        "jp_patron",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"从他身边的几位随从来看，这人的地位应该不算低。",
        "bar_inside_4",
        "xincheng_normal",
        "jp_patron",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"无论如何，林心诚不得不挤出笑脸前去迎接。",
        "bar_inside_4",
        "xincheng_normal",
        "jp_patron",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「几位先生您好！欢迎光顾本店，请问有什么需要帮助的地方吗？」",
        "bar_inside_4",
        "xincheng_smile",
        "jp_patron",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"她并没有使用日语进行问候，这只是单纯地因为她不想这样。",
        "bar_inside_4",
        "xincheng_smile",
        "jp_patron",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"不过看起来那些人中有些懂得中文，并没有因此造成太多的麻烦。",
        "bar_inside_4",
        "xincheng_smile",
        "jp_patron",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"日本军官",
        L"「总共四个人，快给我们找好座位，今天我们要痛快一晚上！」",
        "bar_inside_4",
        "xincheng_smile",
        "jp_patron",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"他们的话语仍然相当粗鲁，但心诚仍然不得不全部照做。",
        "bar_inside_4",
        "xincheng_smile",
        "jp_patron",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「好的好的，请先生们稍作等待，我去通知一下掌柜。」",
        "bar_inside_4",
        "xincheng_smile",
        "jp_patron",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"她知道这种场面必需要母亲出场，尽管她有时并不喜欢林如意的某些处事方式。",
        "bar_inside_4",
        "xincheng_normal",
        "ruyi_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「事情就是这样，」",
        "bar_inside_4",
        "xincheng_normal",
        "ruyi_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林如意",
        L"「我知道了，等我过去照看一下吧。」",
        "bar_inside_4",
        "xincheng_normal",
        "ruyi_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林如意",
        L"「哎呀哎呀！小女不知道大人们前来，招待不周还望见谅了！」",
        "bar_inside_4",
        "jp_patron",
        "ruyi_charming",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"日本军官",
        L"「哈哈哈，来，上四瓶清酒。」",
        "bar_inside_4",
        "jp_patron",
        "ruyi_charming",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林如意",
        L"「好的好的，心诚——」",
        "bar_inside_4",
        "jp_patron",
        "ruyi_charming",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「在，请先生们稍等。」",
        "bar_inside_4",
        "xincheng_normal",
        "ruyi_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"林心诚随即去后厨取来清酒。",
        "bar_inside_4",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"马灵看起来正坐在很远的地方，同时悄悄地观察着这里发生的事情。",
        "bar_inside_4",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"而当她回来的时候，她便看到了这幅景象。",
        "bar_inside_4",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        "None",
        "ruyi_jp_patron",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        "None",
        "ruyi_jp_patron",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"林如意正在和那位日本军官拥抱在一起，相互之间很是亲密。",
        "ruyi_jp_patron",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「酒水到了，还请先生们慢用。」",
        "ruyi_jp_patron",
        "xincheng_smile",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"日本军官",
        L"「好，好，都给端上来吧。」",
        "ruyi_jp_patron",
        "xincheng_smile",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「嗯。」",
        "ruyi_jp_patron",
        "xincheng_smile",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"林心诚想要赶紧离开这个地方，但她也知道这里的条件不允许她这样做。",
        "ruyi_jp_patron",
        "xincheng_smile",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林如意",
        L"「几位大人远道而来，真是辛苦。」",
        "ruyi_jp_patron",
        "xincheng_smile",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林如意",
        L"「心诚，还不快为大人们演奏几曲，多多慰劳慰劳他们呀？」",
        "ruyi_jp_patron",
        "xincheng_smile",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「我知道了，请几位稍等。」",
        "ruyi_jp_patron",
        "xincheng_gently_smile",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"她转身前往前台取来了一支笛子，那是她最为擅长的乐器。",
        "ruyi_jp_patron",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"心诚随即更换了装束回到桌前，开始了她的演奏。",
        "ruyi_jp_patron",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"那笛声清雅、美妙，只可惜欣赏它的人们却是那样的粗野庸碌。",
        "xincheng_flute",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"他们只顾着喝酒，聊起天来总是像争吵似的大吼大叫。",
        "xincheng_flute",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"还有林如意。",
        "xincheng_flute",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"心诚不想继续思考这些了。",
        "xincheng_flute",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"就当作只有自己一个人，就这样自顾自地表演下去吧。",
        "xincheng_flute",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"如同忘却了这个世界，独立于此。",
        "xincheng_flute",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"不久之后，又是一曲终了。",
        "None",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"日本军官",
        L"「呼……」",
        "bar_inside_4",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"桌上几瓶清酒饮尽之后，看起来几位军官已经面露倦色。",
        "bar_inside_4",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"日本军官",
        L"「快给我们准备几个房间，我要去休息一会。」",
        "bar_inside_4",
        "jp_patron",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林如意",
        L"「知道了，请大人们随我这边走。」",
        "bar_inside_4",
        "jp_patron",
        "ruyi_charming",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"林如意于是搀扶着长官向着后店走去。",
        "bar_inside_4",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"他们走得很慢，看起来长官确实是有些醉了吧。",
        "bar_inside_4",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"就在这时，长官小声地向着林如意问道：",
        "bar_inside_4",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"军官",
        L"「今晚的服务……还是照常进行吧。」",
        "bar_inside_4",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林如意",
        L"「我知道的，晚上包您满意。」",
        "bar_inside_4",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"军官",
        L"「哈哈哈」",
        "bar_inside_4",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"他们二人就这样离开了。",
        "bar_inside_4",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「呼……」",
        "bar_inside_4",
        "xincheng_serious",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"在他们走后，林心诚才终于回到了之前的状态。",
        "bar_inside_4",
        "xincheng_serious",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"就在这个时候，马灵突然走了上来，凑在林心诚的耳边轻声说道：",
        "bar_inside_4",
        "xincheng_serious",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「寻芳径……」",
        "bar_inside_4",
        "xincheng_serious",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"是的，这是「海上花」一直以来的暗语。",
        "bar_inside_4",
        "xincheng_serious",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「马先生……？」",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「请问您是需要「那种服务」吗？」",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"马灵他……应该是第一次来海上花才对吧？",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"林心诚有些惊讶，同时又感到相当疑惑。",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「哈哈哈，我暂时还没有那种想法。」",
        "bar_inside_4",
        "xincheng_normal",
        "ling_smile",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「嗯……不过你确实勾起了我的兴趣。」",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「好吧……只是很可惜呀，我可是非卖品。」",
        "bar_inside_4",
        "xincheng_thinking",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「不过嘛」",
        "bar_inside_4",
        "xincheng_gently_smile",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「如果你出的钱足够多的话，倒也不是完全没有可能」",
        "bar_inside_4",
        "xincheng_gently_smile",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「哈哈」",
        "bar_inside_4",
        "xincheng_evil_smile",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「哈哈哈」",
        "bar_inside_4",
        "xincheng_evil_smile",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"随后两人再次回到了角落里的座位，平静地对视许久。",
        "bar_inside_4",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「你……给他们下药了对吧？」",
        "bar_inside_4",
        "ling_normal",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「哎？」",
        "bar_inside_4",
        "xincheng_serious",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「我说的就是刚刚过来的那一批人。」",
        "bar_inside_4",
        "xincheng_serious",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「因为通常而言他们不应该在这么短的时间内变得如此疲倦，更何况只有喝过酒的那三人有这种变化。」",
        "bar_inside_4",
        "xincheng_serious",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「那肯定是因为他们喝醉了吧。」",
        "bar_inside_4",
        "xincheng_evil_smile",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「有没有醉酒这一点我还是可以看得出来的。所以呢？」",
        "bar_inside_4",
        "xincheng_evil_smile",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「你可真是大胆。」",
        "bar_inside_4",
        "xincheng_evil_smile",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「唔……」",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"她随即四下里扫视了一圈，看起来附近都没有人的样子。",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"她随即小声地对马灵说：",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「你到底想怎么样？」",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「哈哈，没什么，我是不会告诉别人的。」",
        "bar_inside_4",
        "xincheng_normal",
        "ling_smile",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「真的嘛？」",
        "bar_inside_4",
        "xincheng_evil_smile",
        "ling_smile",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「当然。」",
        "bar_inside_4",
        "xincheng_evil_smile",
        "ling_smile",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"她当然没有相信，但是事已至此，也只能和面前的这个人继续聊下去了。",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「只是一点小剂量的安眠药。」",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「我可不想这帮人在我们店里闹得太久。」",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「掌柜她知道这件事情吗？」",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「我想你应该不需要问得这么多吧。」",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「好吧……看来你也是不打算给我好脸色看了是吗？」",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「我只是不喜欢过来扰乱店里秩序的人。」",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「扰乱秩序……说的是我吗？还是刚刚来店里的那些人？」",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「半斤八两吧，我觉得。」",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「好吧。」",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「你真的很有趣……不过今晚我就先走一步了，明晚再见吧。」",
        "bar_inside_4",
        "xincheng_normal",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「请您慢走——马灵先生。」",
        "bar_inside_4",
        "xincheng_gently_smile",
        "ling_normal",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"看起来是惹上了一个麻烦人物啊……我还不清楚他的底细，但他似乎懂得很多的样子。",
        "bar_inside_4",
        "xincheng_thinking",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"看来只能明天再继续盘问他了。",
        "bar_inside_4",
        "xincheng_thinking",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"啊，但是他的那个态度真的好讨人厌。",
        "bar_inside_4",
        "xincheng_thinking",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"在此之后，今天的运营工作便一切顺利地结束了。",
        "None",
        "None",
        "None",
        "a_day_in_the_bar"
          );
    },
    [](){
      // 章节结束
      if (is_reviewing) {
        current_state_.chapter_ = -4;
      }
      current_state_.chapter_++;
      current_state_.step_ = 0;
    }
  };
}

vector<function<void()>> GamePlay::init_cp2() {
  return {
    [](){
      ss(
        L"旁白",
        L"……",
        "None",
        "xincheng_thinking",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"……",
        "None",
        "None",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"时间很快就来到了第二天傍晚。",
        "None",
        "None",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"林心诚一边忙着日常的工作，一边等待着那位银发男子的到来。",
        "None",
        "None",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"现在的店里已经相当热闹了。",
        "bar_inside_3",
        "xincheng_serious",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「来了吗？」",
        "bar_inside_3",
        "xincheng_serious",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"她看到了，从门外走进来的这一位客人。",
        "bar_inside_3",
        "xincheng_serious",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"他身着风衣，带着一顶黑色的帽子，有着银色的头发，以及……那种讨人厌的笑容。",
        "bar_inside_3",
        "xincheng_serious",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「嗯……」",
        "bar_inside_3",
        "xincheng_serious",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"不过这一次她只是躲在角落里看着，并没有主动前去接待。",
        "bar_inside_3",
        "xincheng_serious",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「一个人，来一份红茶就好。」",
        "bar_inside_3",
        "waiter",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"服务生",
        L"「好的好的，先生请稍等！」",
        "bar_inside_3",
        "waiter",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"这次是另外一位店员接待了马灵，随后他又坐回了先前的座位。",
        "bar_inside_3",
        "None",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"心诚是在等待马灵主动询问她的情况。",
        "bar_inside_3",
        "None",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"马灵像昨天一样在这里读报，随后便在不经意间问起了林心诚的情况。",
        "bar_inside_3",
        "None",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"看起来他们还算默契。",
        "bar_inside_3",
        "None",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「我记得先前店里还有一位……黑色的小姑娘？」",
        "bar_inside_3",
        "None",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"马灵身边没有其他人，加上他说话时相当小声……",
        "bar_inside_3",
        "None",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"实际上他就是想要说给本人听吧。",
        "bar_inside_3",
        "None",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「请问你是在找我吗？」",
        "bar_inside_3",
        "xincheng_gently_smile",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「我叫做林心诚，往后叫我心诚就好。」",
        "bar_inside_3",
        "xincheng_gently_smile",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"她早就藏在吧台边上，现在则是刚刚现身。",
        "bar_inside_3",
        "xincheng_gently_smile",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「请问这位客人有什么需求吗？」",
        "bar_inside_3",
        "xincheng_smile",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「哈哈，插科打诨就不必了，来，坐到这边来吧。」",
        "bar_inside_3",
        "xincheng_smile",
        "ling_smile",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「好的。」",
        "bar_inside_3",
        "xincheng_gently_smile",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"她并没有多问，就顺势坐到了马灵的身边。",
        "bar_inside_3",
        "None",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「嗯……」",
        "ling_in_the_bar",
        "xincheng_thinking",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「我们想想看来聊点什么？」",
        "ling_in_the_bar",
        "xincheng_thinking",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"想知道的事情可太多了，不过最好还是从一些无关紧要的事情开始吧。",
        "ling_in_the_bar",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「你之前……说觉得我很有趣，这是什么意思？」",
        "ling_in_the_bar",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「哈哈，那个啊」",
        "ling_in_the_bar",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「我想知道……心诚你今年多少岁了？」",
        "ling_in_the_bar",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「十四岁。怎么了？」",
        "ling_in_the_bar",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「嗯。我觉得你年纪轻轻就这样厉害，未来可是大有可为。」",
        "ling_in_the_bar",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「这样的人可不多见，因此会令人觉得相当有趣吧。」",
        "ling_in_the_bar",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「谢谢你呀。我就当作这是对我的夸奖好了。」",
        "ling_in_the_bar",
        "xincheng_serious",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"实际上因为自己的小动作被对方所识破，还是稍微有一点不太开心。",
        "ling_in_the_bar",
        "xincheng_serious",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「这也让我开始好奇你的故事了。」",
        "ling_in_the_bar",
        "xincheng_serious",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「不过这和你没有什么关系，对吧？」",
        "ling_in_the_bar",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「哈哈，可以这样说。」",
        "ling_in_the_bar",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「看起来你每天都过得很清闲，一副无所事事的样子。」",
        "ling_in_the_bar",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「你应该刚到这里没有多久对吧，这样悠闲的生活在现在可不容易呀。」",
        "ling_in_the_bar",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"她其实是有意地把话题朝着这个方向带去。",
        "ling_in_the_bar",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「你很好奇，是吗？」",
        "ling_in_the_bar",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「看起来你还是不大愿意说的样子。」",
        "ling_in_the_bar",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「我明白的，我就不再追问了吧。毕竟每个人都会有一些不便言说的事情。」",
        "ling_in_the_bar",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「你可真是一点都不像是个小孩子。」",
        "ling_in_the_bar",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「怎么这样说呢？」",
        "ling_in_the_bar",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「因为你心理太成熟了一些。」",
        "ling_in_the_bar",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「「不便言说」这一点对于小孩子来说恐怕是一件无法理解的事情吧。」",
        "ling_in_the_bar",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「哈……那是因为他们太天真了吧。」",
        "ling_in_the_bar",
        "xincheng_serious",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「只是现在的我并不像他们那样笨。」",
        "ling_in_the_bar",
        "xincheng_serious",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"心诚转过身，望向酒馆当中。",
        "bar_inside_3",
        "xincheng_serious",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「沉默与谎言……大人们的世界里总是充斥着这些。」",
        "bar_inside_3",
        "xincheng_thinking",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「当然也只有学会了这两项技能，才能称得上心态成熟吧。」",
        "bar_inside_3",
        "xincheng_thinking",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「这无可厚非，不过是危险世界中自我保护的手段而已。」",
        "bar_inside_3",
        "xincheng_thinking",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「嗯……」",
        "bar_inside_3",
        "xincheng_thinking",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「你应该已经知道了「海上花」平日里的主要营收所在。」",
        "bar_inside_3",
        "xincheng_serious",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「你觉得这里的人们当中，有多少也同样知道这一点呢？」",
        "bar_inside_3",
        "xincheng_serious",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「但是大家心照不宣，甚至有时我们自己在酒馆的工作当中，都会忘记自己做过的事情。」",
        "bar_inside_3",
        "xincheng_thinking",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「但是我们从不去想，就这样度过一晚又一晚的时光。」",
        "bar_inside_3",
        "xincheng_thinking",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「忙碌……同时又和谐、快乐着呐。」",
        "bar_inside_3",
        "xincheng_thinking",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「如果说人们终究要死去的话，那么幸福才是最大的谎言吧。」",
        "bar_inside_3",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「当人们贪杯享乐的时候，自然不会去想象病痛与死亡。」",
        "ling_in_the_bar",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「最终的结局已然注定，人们从来无力改变，至多只能试着遗忘。」",
        "ling_in_the_bar",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「就这样自我满足，自我欺骗。」",
        "ling_in_the_bar",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「人们的「幸福」不过就是这样一回事而已吧。」",
        "ling_in_the_bar",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「……」",
        "ling_in_the_bar",
        "xincheng_serious",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「抱歉，不小心说得太多了。」",
        "ling_in_the_bar",
        "xincheng_serious",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「我知道了……」",
        "ling_in_the_bar",
        "xincheng_thinking",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「……」",
        "bar_inside_3",
        "None",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「像极了六朝时人们相互之间的玄谈。」",
        "bar_inside_3",
        "None",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「只是因为无力改变现实，而只能期望着忘却这一切。」",
        "bar_inside_3",
        "None",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「而如今的社会嘛……」",
        "bar_inside_3",
        "None",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「也就那样吧。」",
        "bar_inside_3",
        "xincheng_thinking",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「说的也是呀。」",
        "bar_inside_3",
        "xincheng_thinking",
        "ling_smile",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「所以……」",
        "bar_inside_3",
        "xincheng_serious",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「你我萍水相逢，许多事还是不多过问为好。」",
        "bar_inside_3",
        "xincheng_serious",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「知道太多才是不幸的根源呢。」",
        "bar_inside_3",
        "xincheng_serious",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「好吧……不过你真的这样想吗？」",
        "bar_inside_3",
        "xincheng_serious",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「也许吧。」",
        "bar_inside_3",
        "xincheng_serious",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"随后，林心诚便起身离开，前去服务其他顾客了。",
        "bar_inside_3",
        "None",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「这位客人您好！请问有什么需要吗？」",
        "bar_inside_3",
        "xincheng_smile",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"此后两人之间也有一些言语，不过多是无关紧要之事。",
        "bar_inside_3",
        "None",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"忙碌一整天之后，马灵便要准备离开了。",
        "bar_inside_3",
        "None",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「马灵先生你也要走了吗？」",
        "bar_inside_3",
        "xincheng_normal",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「嗯，时间也已经不早了。」",
        "bar_inside_3",
        "xincheng_normal",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「那么……马灵先生再见，也欢迎下次光临！」",
        "bar_inside_3",
        "xincheng_gently_smile",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「好啊。」",
        "bar_inside_3",
        "xincheng_gently_smile",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「嗯……不过下次需要等到什么时候呢？明天你会不会再来？」",
        "bar_inside_3",
        "xincheng_thinking",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「哈哈，如果你想的话，明天再来一趟也没问题。」",
        "bar_inside_3",
        "xincheng_thinking",
        "ling_smile",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「怎么说话的呢……」",
        "bar_inside_3",
        "xincheng_serious",
        "ling_smile",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"不过那个人……也是真的很有趣。",
        "bar_inside_3",
        "xincheng_serious",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"今日的工作到此结束。",
        "bar_inside_3",
        "None",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"看起来是相当平静而且收获颇丰的一天呢。",
        "bar_inside_3",
        "None",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"第二天也很快就到来了。",
        "bar_inside_3",
        "None",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"今天的生意依然相当好。",
        "bar_inside_5",
        "None",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"随后不出意外地……那个人又一次出现在了「海上花」。",
        "bar_inside_5",
        "None",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"常来酒馆，却从不饮酒的奇怪家伙。",
        "bar_inside_5",
        "None",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「欢迎光临！」",
        "bar_inside_5",
        "xincheng_gently_smile",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「跟之前一样，一杯红茶。」",
        "bar_inside_5",
        "xincheng_gently_smile",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"这一次林心诚亲自去接待了他。",
        "bar_inside_5",
        "xincheng_gently_smile",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"他仍然坐在先前的位置上，不过这一次没有读报纸，而是带来了一本书。",
        "bar_inside_5",
        "xincheng_gently_smile",
        "ling_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"他看起来相当专注。",
        "ling_in_the_bar_2",
        "xincheng_gently_smile",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"心诚需要去忙店里杂务，不过当她稍微闲下来时，便会坐到马灵的身边与他闲聊起来。",
        "bar_inside_5",
        "xincheng_gently_smile",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「你在读什么呢？」",
        "ling_in_the_bar_2",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「只是一些文艺作品，嗯……言情小说，你喜欢吗？」",
        "ling_in_the_bar_2",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「可真是悠闲呢。」",
        "ling_in_the_bar_2",
        "xincheng_evil_smile",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「哈哈。」",
        "ling_in_the_bar_2",
        "xincheng_evil_smile",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「那么你怎么样呢，会不会经常看书？」",
        "ling_in_the_bar_2",
        "xincheng_evil_smile",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「我么？说起来其实和你也差不多吧。」",
        "ling_in_the_bar_2",
        "xincheng_serious",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「经常会读一点东西，不过也没有什么目的，单纯打发时间而已。」",
        "ling_in_the_bar_2",
        "xincheng_serious",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「哎……」",
        "ling_in_the_bar_2",
        "xincheng_thinking",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「怎么了？」",
        "ling_in_the_bar_2",
        "xincheng_thinking",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「在别人面前一直保持微笑也是很累的呀。」",
        "ling_in_the_bar_2",
        "xincheng_thinking",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「哈哈，不过现在你在我面前倒是一点也不喜欢笑的样子。」",
        "ling_in_the_bar_2",
        "xincheng_thinking",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「怎么啦？难道我一直保持这样的表情才能让你开心吗？」",
        "ling_in_the_bar_2",
        "xincheng_evil_smile",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「还是算了吧……这样真的很累，也稍微让我休息一会吧。」",
        "ling_in_the_bar_2",
        "xincheng_thinking",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「而且在你面前的话……我觉得没有这个必要。」",
        "ling_in_the_bar_2",
        "xincheng_serious",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「嗯……」",
        "ling_in_the_bar_2",
        "xincheng_serious",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「是啊，真的辛苦你了。」",
        "ling_in_the_bar_2",
        "xincheng_serious",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「就来这里坐坐，稍稍歇息一下吧。」",
        "ling_in_the_bar_2",
        "xincheng_serious",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"在此后一段时间里，两人之间都没有什么言语。",
        "ling_in_the_bar_2",
        "None",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"安静、祥和，又轻松愉悦，让人想要一直停留在这样的时刻。",
        "ling_in_the_bar_2",
        "None",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"但是这注定无法成为现实。",
        "None",
        "None",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林如意",
        L"「心诚，有贵客光顾了！」",
        "bar_inside_3",
        "None",
        "ruyi_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「哎？」",
        "bar_inside_3",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"听到掌柜的呼唤，她顺势朝着正门的方向望去。",
        "bar_inside_3",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"看起来是过来了一位「洋大人」。",
        "bar_inside_3",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「稍等，我过去一下。」",
        "bar_inside_3",
        "xincheng_serious",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"客人",
        L"「来来，直接把店里最好的酒都端上来。」",
        "bar_inside_3",
        "None",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林如意",
        L"「好的好的，稍后就来，客官莫要心急——心诚？」",
        "bar_inside_3",
        "None",
        "ruyi_normal",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「来了！」",
        "bar_inside_3",
        "xincheng_normal",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"她很快取来了上好的白酒，送与这位来客。",
        "bar_inside_3",
        "None",
        "None",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"他看起来是一个美国人，从穿着来看，是一幅富裕无比的样子。",
        "bar_inside_3",
        "None",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「先生请慢用！」",
        "bar_inside_3",
        "xincheng_smile",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"客人",
        L"「哦……」",
        "bar_inside_3",
        "xincheng_smile",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「哎……请问先生怎么了？」",
        "bar_inside_3",
        "xincheng_thinking",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"客人",
        L"「哈哈，林如意，以前我还没有怎么注意到。」",
        "bar_inside_3",
        "xincheng_thinking",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"客人",
        L"「没想到你家里的大女儿已经长得这么大了。」",
        "bar_inside_3",
        "xincheng_thinking",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"客人",
        L"「看起来颇有几分姿色呢。」",
        "bar_inside_3",
        "xincheng_normal",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林如意",
        L"「哈哈，多谢大人褒奖了！」",
        "bar_inside_3",
        "None",
        "ruyi_charming",
        "another_day_in_the_bar"
          );
    },
     [](){
      ss(
        L"林如意",
        L"「小女林心诚今年刚刚满十四周岁，正是身材美貌刚刚崭露头角的时候呢。」",
        "bar_inside_3",
        "None",
        "ruyi_charming",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林如意",
        L"「来，心诚，还不快出来见见大人？」",
        "bar_inside_3",
        "None",
        "ruyi_charming",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"林如意说着，随手便将林心诚推至身前。",
        "bar_inside_3",
        "None",
        "ruyi_charming",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「哎……哎！」",
        "bar_inside_3",
        "xincheng_smile",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"尽管是被迫而为，心诚还是不得不摆出满脸的笑容。",
        "bar_inside_3",
        "xincheng_smile",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"客人",
        L"「哈哈哈，不错不错。」",
        "bar_inside_3",
        "xincheng_smile",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"客人",
        L"「怎么样，想过来我身边坐坐吗？」",
        "bar_inside_3",
        "xincheng_smile",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「这个嘛……」",
        "bar_inside_3",
        "xincheng_evil_smile",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「哎！」",
        "bar_inside_3",
        "xincheng_evil_smile",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"等不到她作出表态，林如意便再次将她向前推去",
        "bar_inside_3",
        "xincheng_evil_smile",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「这位客人……唔」",
        "bar_inside_3",
        "xincheng_serious",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"客人",
        L"「哈哈，你可真是太美妙了。」",
        "bar_inside_3",
        "None",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"看起来这位客人已经如愿以偿，紧紧地抱住了林心诚的身体。",
        "bar_inside_3",
        "None",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"随后他便开始动手，对她的身子上下摸索。",
        "bar_inside_3",
        "None",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「唔……」",
        "bar_inside_3",
        "None",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"她想要叫出声来，但她知道此时的情形不会允许她做这些。",
        "bar_inside_3",
        "None",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"想要……求救吗？",
        "bar_inside_3",
        "None",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"但是当她看向林如意，却只见到对方满脸微笑的神情。",
        "bar_inside_3",
        "None",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"为什么会这样呢？",
        "bar_inside_3",
        "None",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
     [](){
      ss(
        L"旁白",
        L"仿佛她只是期望着，让心诚再往对方的身上贴得更加紧密一点，将全身心都奉献给对方才好。",
        "bar_inside_3",
        "None",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
     [](){
      ss(
        L"林心诚",
        L"为什么会这样呢……妈妈？",
        "bar_inside_3",
        "None",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"那位客人开始将另一只手伸了过来。",
        "bar_inside_3",
        "None",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"从上面开始抚摸……一直到身下。",
        "bar_inside_3",
        "None",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"马灵……他在哪里？",
        "bar_inside_3",
        "None",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"他正在看着我吗？",
        "bar_inside_3",
        "None",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"请不要这样……不要看……求求你了。",
        "bar_inside_3",
        "None",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
     [](){
      ss(
        L"旁白",
        L"她很想要哭泣，但最终却仍旧忍耐住了，而没有什么过激的反应。",
        "bar_inside_3",
        "None",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"所剩下的只有沉默……而已。",
        "bar_inside_3",
        "None",
        "patron_1",
        "another_day_in_the_bar"
          );
    },
    [](){
      ss(
        L"旁白",
        L"其实也没有什么大不了的对吗？",
        "None",
        "None",
        "None",
        "warm_hugging"
          );
    },
     [](){
      ss(
        L"旁白",
        L"毕竟这里是「海上花」，隐忍也是学习的一部分……它也是「海上花」所赖以生存与繁荣的基本。",
        "None",
        "None",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"旁白",
        L"如果要成为未来的接班人的话，这一点是必然要了解的……林如意一定就是这样想的吧。",
        "None",
        "None",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"旁白",
        L"……",
        "bar_inside_3",
        "None",
        "patron_1",
        "warm_hugging"
          );
    },
     [](){
      ss(
        L"旁白",
        L"终于，过去很长时间之后，似乎是玩腻了，又像是终于提起兴致了一样。",
        "bar_inside_3",
        "None",
        "patron_1",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"旁白",
        L"他放开了林心诚，让她得以脱身，此后便前往后店去了。",
        "bar_inside_3",
        "None",
        "patron_1",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"旁白",
        L"再没有多说什么，心诚又一次回到了马灵的位置。",
        "bar_inside_3",
        "xincheng_thinking",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「唉……」",
        "ling_in_the_bar_2",
        "None",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「怎么了，像这样叹气？」",
        "ling_in_the_bar_2",
        "xincheng_serious",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「很抱歉……我什么也没能帮到你。」",
        "ling_in_the_bar_2",
        "xincheng_serious",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「没事啦……你不用这样自责。」",
        "ling_in_the_bar_2",
        "xincheng_thinking",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「这只是再常见不过的事情而已，如果你闹出什么乱子来的话我们反而更加不好处理。」",
        "ling_in_the_bar_2",
        "xincheng_thinking",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「就这样忘掉它吧，刚刚……什么也没有发生过。」",
        "ling_in_the_bar_2",
        "xincheng_normal",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「唉……」",
        "ling_in_the_bar_2",
        "xincheng_thinking",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"旁白",
        L"就这样……又一声叹气过后，心诚就背对着马灵，坐在了他的身边。",
        "ling_in_the_bar_2",
        "xincheng_thinking",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"旁白",
        L"……",
        "None",
        "None",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「唔……」",
        "None",
        "xincheng_serious",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「违法的哦……」",
        "None",
        "xincheng_serious",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"旁白",
        L"原来是马灵……他用双手从身后抱起了林心诚，俯下身体紧贴着心诚的背部。",
        "None",
        "xincheng_serious",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"旁白",
        L"不过她并没有做出任何反抗的意思，而是转过身来，正对着马灵，同时用自己的双手紧紧地抱住了他。",
        "None",
        "xincheng_serious",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「这么喜欢占我便宜呀……好吧」",
        "None",
        "xincheng_thinking",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「唔……」",
        "None",
        "xincheng_thinking",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「可以……」",
        "None",
        "xincheng_serious",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「哭吗？」",
        "None",
        "xincheng_serious",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「可以的哦。」",
        "None",
        "xincheng_serious",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「嗯……」",
        "None",
        "xincheng_thinking",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「呜呜……呜呜呜……」",
        "None",
        "xincheng_sad",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"旁白",
        L"……",
        "None",
        "None",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"旁白",
        L"心诚哭得相当小声……只有马灵一个人能够听得见。",
        "xincheng_ling_hugging_crying",
        "None",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"旁白",
        L"她已经不记得上一次这样哭闹是在什么时候了。",
        "xincheng_ling_hugging_crying",
        "None",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"旁白",
        L"但是这样做一次……真的让人很痛快，很是尽兴呢。",
        "xincheng_ling_hugging_crying",
        "None",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"旁白",
        L"说是想要将这些事情通通遗忘，这又怎么可能呢？",
        "xincheng_ling_hugging_crying",
        "None",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"旁白",
        L"不过是在一个思想都不被允许的时代里，刻意装作自己一无所知的样子罢了。",
        "xincheng_ling_hugging_crying",
        "None",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"旁白",
        L"……",
        "xincheng_ling_hugging_crying",
        "None",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"旁白",
        L"她真的为此感到由衷的幸福。",
        "xincheng_ling_hugging_crying",
        "None",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"旁白",
        L"在最近的许多年来，都还是头一次有这样的感觉。",
        "xincheng_ling_hugging_crying",
        "None",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"旁白",
        L"真的只是哭出来了而已。",
        "xincheng_ling_hugging_crying",
        "None",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"旁白",
        L"……",
        "xincheng_ling_hugging_crying",
        "None",
        "None",
        "warm_hugging"
          );
    },
    [](){
      ss(
        L"旁白",
        L"……",
        "xincheng_ling_hugging_crying",
        "None",
        "None",
        "warm_hugging"
          );
    },
    [](){
      // 章节结束
      if (is_reviewing) {
        current_state_.chapter_ = -4;
      }
      current_state_.chapter_++;
      current_state_.step_ = 0;
    }
  };
}

vector<function<void()>> GamePlay::init_cp3() {
  return {
    [](){
      ss(
        L"旁白",
        L"在那之后马灵也常常会前来光顾——准确来说其实是每晚都会来。",
        "None",
        "None",
        "None",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"心诚也总会去和他聊天，那可是辛苦工作里少有的闲暇时光。",
        "None",
        "None",
        "None",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"今天晚上也是一样。",
        "None",
        "None",
        "None",
        "departure"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「一杯红茶就好。」",
        "bar_inside_1",
        "None",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「好——知道了。」",
        "bar_inside_1",
        "xincheng_gently_smile",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"虽然每晚都出入酒吧，但是马灵却从来不饮酒。",
        "bar_inside_1",
        "xincheng_gently_smile",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"这在心诚看来相当不错，毕竟比起酒气熏天的人来说，和不饮酒的人待在一起确实会舒适很多。",
        "bar_inside_1",
        "xincheng_gently_smile",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"尽管他们已经相处许久，但是对于彼此的情况却少有了解。",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"一种独特的……陌生人之间的感情嘛？",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"这只是一种沉默的保护色。",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"毕竟，如果谁首先将其捅破的话，这种无知的幸福恐怕就会从此不复存在了。",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"但是他们二人……会接受彼此就一直这样下去吗？。",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"任何进一步的想法，都会招致危险的。",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"林心诚……她当然已经预想到了，也许马灵的工作内容并不简单。",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"如果自己牵涉过多的话……未来会因此向着何处发展去呢？",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「呐，马灵。」",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「你到上海这边来，打算待到什么时候，到底是做什么的呢？」",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「我么？」",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"他放低了声音，凑到林心诚的耳边对她说：",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「我是国民政府军统的特务，目前还有任务在身，会继续待在上海。」",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「等待这些结束之后，我也不知道自己会到哪里去。」",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「这样吗……」",
        "bar_inside_1",
        "xincheng_thinking",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「不过这种事情你就直白地和我说，不怕我向皇军报告吗？」",
        "bar_inside_1",
        "xincheng_thinking",
        "ling_normal",
        "departure"
          );
    },
     [](){
      ss(
        L"马灵",
        L"「当然不会有这种事……我相信自己看人不会错的。」",
        "bar_inside_1",
        "xincheng_thinking",
        "ling_normal",
        "departure"
          );
    },
     [](){
      ss(
        L"林心诚",
        L"「嗯……我保证。」",
        "bar_inside_1",
        "xincheng_gently_smile",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「所以说……为什么你会想要做这种工作呢？」",
        "bar_inside_1",
        "xincheng_normal",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「因为我自己的理想吧。」",
        "bar_inside_1",
        "xincheng_normal",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「因为对于时代诸多不满，所以会想要尽己所能让世界做出改变。」",
        "bar_inside_1",
        "xincheng_normal",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「让世界做出改变嘛……」",
        "bar_inside_1",
        "xincheng_thinking",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「听起来像是还没脱离稚气的小孩子才会说的话呢。」",
        "bar_inside_1",
        "xincheng_evil_smile",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「哈哈，是啊……不过我确实一直这样相信着呢。」",
        "bar_inside_1",
        "xincheng_evil_smile",
        "ling_smile",
        "departure"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「你今年……只有十四周岁，对吗？」",
        "bar_inside_1",
        "xincheng_evil_smile",
        "ling_smile",
        "departure"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「不觉得你一直以来都过得太现实了一些吗？」",
        "bar_inside_1",
        "xincheng_evil_smile",
        "ling_smile",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「是的呀……」",
        "bar_inside_1",
        "xincheng_serious",
        "ling_smile",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「我只是早早认清了现实的模样……明白自己的无能之后，自然不会有那么多不切实际的幻想。」",
        "bar_inside_1",
        "xincheng_serious",
        "ling_smile",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「那么你又怎么样呢？虽然想得这么多，你自己一个人又能做到什么？」",
        "bar_inside_1",
        "xincheng_serious",
        "ling_smile",
        "departure"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「你知道「石见昭夫」这个人吗？」",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「哎……？」",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"她当然知道石见昭夫。",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"他可是「海上花」里的常客，如今已经做到了日军师长的位置上。",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"位高权重的同时……又与林如意有过一些私交。",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"他从来不和通常客人一样借由正店人员进行交易，而是有着自己的途径，秘密出入于「海上花」的后店。",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「你到底想要做什么？」",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「我需要找到机会，将他置于死地。」",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「你当真的吗？」",
        "bar_inside_1",
        "xincheng_firm",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"因为身处于这样高位的军官，身边安保措施极其严密，平时若是想要接近他必定绝无可能。",
        "bar_inside_1",
        "xincheng_firm",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"但如果是在店里寻欢作乐的时候，他自然不会在身边安排任何人进行防卫。",
        "bar_inside_1",
        "xincheng_firm",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"此时如果能够得到店里人员的帮助的话，很容易就能有得手的机会了。",
        "bar_inside_1",
        "xincheng_firm",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"相比马灵是早早就做好了这些信息的搜查工作了吧。",
        "bar_inside_1",
        "xincheng_firm",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「所以说，这才是你到「海上花」这里来的最终目的吧。」",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「还有这样费心地想要和我处好关系……也是。」",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「不完全是这样吧。」",
        "bar_inside_1",
        "xincheng_serious",
        "ling_smile",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"他说得相当平淡的样子。",
        "bar_inside_1",
        "xincheng_serious",
        "ling_smile",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「你有想过像这样做的后果吗？」",
        "bar_inside_1",
        "xincheng_thinking",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「如果你做了这样的事情，之后日军会做何反应，「海上花」要怎么办？」",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「你又要怎么办呢？」",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「十条命都不够你死的。」",
        "bar_inside_1",
        "xincheng_serious",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「说的也是呀。」",
        "bar_inside_1",
        "xincheng_serious",
        "ling_smile",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"他还是一副无所谓的样子。",
        "bar_inside_1",
        "xincheng_serious",
        "ling_smile",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「真的只是为了你的那点理想吗？」",
        "bar_inside_1",
        "xincheng_serious",
        "ling_smile",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「哎……」",
        "bar_inside_1",
        "xincheng_thinking",
        "ling_smile",
        "departure"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「我只是不喜欢对着别人卑躬屈膝。」",
        "bar_inside_1",
        "xincheng_thinking",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「我愿意为了自由做出反抗，这点代价自然不足惋惜。」",
        "bar_inside_1",
        "xincheng_thinking",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"马灵",
        L"「不过不知道你是怎样想的呢？」",
        "bar_inside_1",
        "xincheng_thinking",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「唉……」",
        "bar_inside_1",
        "xincheng_thinking",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"她背过身去，走出几步之后，回应说——",
        "bar_inside_1",
        "xincheng_thinking",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「容我再考虑考虑吧。」",
        "bar_inside_1",
        "xincheng_thinking",
        "ling_normal",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"看起来马灵猜的很对。",
        "None",
        "None",
        "None",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"如果换做是掌柜林如意的话，她必定不会支持马灵的行为。",
        "None",
        "None",
        "None",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"但如果是想要获取心诚的帮助的话，则会容易得多了。",
        "None",
        "None",
        "None",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"到了第二天，心诚将马灵带到了自己的房间里去。",
        "None",
        "None",
        "None",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「我知道的……所以我会支持你。」",
        "bedroom",
        "xincheng_serious",
        "None",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「但你得知道这并不是因为你对我的花言巧语，而是因为一些个人恩怨。」",
        "bedroom",
        "xincheng_serious",
        "None",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「「石见昭夫」他曾经……侵犯过我的妈妈。」",
        "bedroom",
        "xincheng_serious",
        "None",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「……我对你总共有两点要求」",
        "bedroom",
        "xincheng_serious",
        "None",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「第一点，绝对不能让「海上花」沾染血迹。」",
        "bedroom",
        "xincheng_serious",
        "None",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「需要给我们提供机会撇清关系。」",
        "bedroom",
        "xincheng_serious",
        "None",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「第二点……」",
        "bedroom",
        "xincheng_serious",
        "None",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「请你一定要平安归来……」",
        "bedroom",
        "xincheng_thinking",
        "None",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"对方同样是非常轻松地答应了。",
        "bedroom",
        "xincheng_thinking",
        "None",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"即使谁都明白，这种要求从来没有那么容易实现。",
        "bedroom",
        "xincheng_thinking",
        "None",
        "departure"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「好吧……」",
        "bedroom",
        "xincheng_serious",
        "None",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"……",
        "None",
        "None",
        "None",
        "departure"
          );
    },
    [](){
      ss(
        L"旁白",
        L"时间没有过去多久。",
        "None",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"一名日军高官被发现死在街头。",
        "officer_died_on_the_street",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"「石见昭夫」遭遇暗杀的消息不胫而走。",
        "officer_died_on_the_street",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"他们开始动员大量人力展开搜查。",
        "officer_died_on_the_street",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"很快，就在当天下午，就传来了犯人被抓获的消息。",
        "officer_died_on_the_street",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"据人们所传，这名犯人的名字就叫做「马灵」。",
        "officer_died_on_the_street",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"但是事情肯定不会这样轻易结束，反间谍活动一旦开始，至少也要抓到大批民众一同殉葬。",
        "officer_died_on_the_street",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"很快又到了晚上的营业时间。",
        "bar_inside_6",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"看起来马灵做得相当好，「海上花」当中没有因此留下任何痕迹。",
        "bar_inside_6",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"因此在中午前来搜查的队伍过来时能够被成功糊弄过去。",
        "bar_inside_6",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"在那之后就有传来犯人落网的消息，顺利地帮她们转移了注意力。",
        "bar_inside_6",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「只是不知道后续要怎么办呢……」",
        "bar_inside_6",
        "xincheng_serious",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"林心诚尽可能地装作一无所知的样子，继续做着酒馆里的工作。",
        "bar_inside_6",
        "xincheng_serious",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"但是马灵他……真的这样容易就被抓到了吗？",
        "bar_inside_6",
        "xincheng_serious",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"但她真的对那个人一无所知。",
        "bar_inside_6",
        "xincheng_serious",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"甚至不知道应该去哪里寻找他的下落。",
        "bar_inside_6",
        "xincheng_serious",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"心诚所能做的就只有等待而已了。",
        "bar_inside_6",
        "xincheng_serious",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"林心诚",
        L"「唔……」",
        "bar_inside_6",
        "xincheng_serious",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"只是这一次，心诚一直等到了深夜打烊后，也没能等到他的到来。",
        "bar_inside_6",
        "xincheng_serious",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"危险的脚步越来越近了。",
        "None",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"她能够隐隐感觉到这一点。",
        "None",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"明天往后……「海上花」这间店里的人们又将走向何方呢？",
        "None",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"……",
        "None",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      ss(
        L"旁白",
        L"未完待续。",
        "None",
        "None",
        "None",
        "a_quiet_day"
          );
    },
    [](){
      // 章节结束
      if (is_reviewing) {
        current_state_.chapter_ = -4;
      }
      current_state_.chapter_++;
      current_state_.step_ = 0;
    }
  };
}

#ifdef __APPLE__
auto const GamePlay::cp0 = init_cp0();
auto const GamePlay::cp1 = init_cp1();
auto const GamePlay::cp2 = init_cp2();
auto const GamePlay::cp3 = init_cp3();
#endif

#ifdef _WIN32
const std::vector<std::function<void()>> GamePlay::cp0 = init_cp0();
const std::vector<std::function<void()>> GamePlay::cp1 = init_cp1();
const std::vector<std::function<void()>> GamePlay::cp2 = init_cp2();
const std::vector<std::function<void()>> GamePlay::cp3 = init_cp3();
#endif

// 实现游戏内容的初始化工作。
